### ISSUE TITLE
VueTS & Vue 0.11

### ISSUE THREAD

**Issue by yyx990803** [diverted247/vuets#1]
Hey Ted, congrats on launching Expressionery! Just want to drop a line regarding Vue 0.11 - would love to see this repo get updated for that :) (Currently only at 0.11.0-rc, but actual release won't introduce any additional API changes)

**Comment by diverted247** [comment]
Will do that soon. We are moving to Austin TX this week so I am off til
10/8 but should be able to make these changes.

Our team has been impressed with Vue and we will be using it as default
from now on. Walmart release is up next.

Regards,

Ted :)

**Comment by diverted247** [comment]
Updated VueTS with Vue 10.6 support and added libs via bower
