### ISSUE TITLE
0.11

### ISSUE THREAD

**Issue by jariz** [diverted247/vuets#3]
Vue was recently updated to 0.11, re-factoring it's config API, adding the deep parameter to $watch, [and many, many other new things](https://github.com/yyx990803/vue/blob/master/changes.md).  
I hope vuets can be upgraded to 0.11 because I'm currently using a modified version to make my TS compile.

**Comment by diverted247** [comment]
Working on 0.11 support today. There is a new issue via .extends I need to get sorted.

**Comment by jariz** [comment]
Awesome man, much appreciated!
